### ISSUE TITLE
Proposal: api design

### ISSUE THREAD

**Issue by tamalsaha** [kube-ci/git-apiserver#2]
```
CRD

apiVersion: git.kube.ci/v1alpha1
kind: Repository
metadata:
  name: appscode-voyager
spec:
  url: https://github.com/appscode/voyager.git
  secret:
    name:
    namespace:
status:
  conditions:
  - status: clone complete
  - status: node xyz assigned
  - status: ready
---------------------------------------

kubectl get branches <---------- x
kubectl get prs <---------- x


kubectl get branches -l repo=appscode-voyager
kubectl get prs -l repo=appscode-voyager

kubectl get commits -l repo=appscode-voyager,branch=master



apiVersion: git.kube.ci/v1alpha1
kind: Branch
metadata:
  uuid:
  resourceversion:
  generation:

  name: appscode-voyager.branch
  labels:
    repo: appscode-voyager
spec:
  fullName: feature/branch-name
  commits:
  - c1
  - c2


apiVersion: git.kube.ci/v1alpha1
kind: PullRequest
metadata:
  name: appscode-voyager.#pr
  labels:
    repo: appscode-voyager
  creationTimestamp:
spec:
  title: xyz
  commits:
  - c1
  - c2
  tags:
  -size/XXL
  reviewers:
  -


apiVersion: git.kube.ci/v1alpha1
kind: Tag
```
